[package]
name = "spotter-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
test-support = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "spotter-cli"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
rpassword = { workspace = true }
serde_json = { workspace = true }
spotter-core = { path = "../spotter-core" }

[target.'cfg(windows)'.dependencies]
spotter-win32 = { path = "../spotter-win32" }
windows = { workspace = true }
windows-service = { workspace = true }

[build-dependencies]
spotter-build = { path = "../spotter-build" }

[dev-dependencies]
spotter-svc = { path = "../spotter-svc" }
tokio = { workspace = true }
