[package]
name = "spotter-svc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
test-support = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "spotter-svc"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
getrandom = { workspace = true }
reqwest = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spotter-core = { path = "../spotter-core" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
toml = { workspace = true }

[target.'cfg(windows)'.dependencies]
spotter-win32 = { path = "../spotter-win32" }
wmi = { workspace = true }
windows = { workspace = true }
windows-service = { workspace = true }

[build-dependencies]
spotter-build = { path = "../spotter-build" }

[dev-dependencies]
tempfile = { workspace = true }
wiremock = { workspace = true }
